# Generated by Django 4.0.4 on 2022-05-24 18:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('area', models.CharField(max_length=20)),
                ('sucursal', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=20)),
                ('operativo', models.BooleanField(default=True)),
                ('nuevo', models.BooleanField(default=True)),
                ('observaciones', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Num_telefono',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('numero_tel', models.CharField(max_length=10, unique=True)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('serie', models.CharField(max_length=20, unique=True)),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor', models.IntegerField(blank=True)),
                ('imei_1', models.IntegerField(blank=True, null=True)),
                ('imei_2', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=50)),
                ('Telefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.num_telefono')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.departamentos')),
            ],
        ),
        migrations.CreateModel(
            name='historial',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha_recepcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.equipos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='equipos',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.series'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.usuarios'),
        ),
    ]
