# Generated by Django 4.1.7 on 2023-03-23 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sma', models.DateField(blank=True, default=None, null=True)),
                ('fecha_ta', models.DateField(blank=True, default=None, null=True)),
                ('fecha_nt', models.DateField(blank=True, default=None, null=True)),
                ('fecha_cm', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camionetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('mantencion', models.DateField()),
                ('observaciones_camionetas', models.CharField(max_length=50)),
                ('modalidad', models.CharField(choices=[('Leasing', 'Leasing'), ('Rental', 'Rental Car')], max_length=20, verbose_name='listado modalidades')),
                ('vin', models.CharField(max_length=20, unique=True)),
                ('kilometraje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('Administracion', 'Administracion'), ('Terreno', 'Terreno'), ('Planta', 'Planta')], max_length=20, null=True, verbose_name='Listado Areas')),
                ('sucursal', models.CharField(choices=[('Bulnes', 'Bulnes'), ('Talca', 'Talca'), ('Chillan', 'Chillan'), ('Peru', 'Peru')], max_length=20, verbose_name='listado sucursales')),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_equipos', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_modelo', models.CharField(max_length=20, unique=True)),
                ('m_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.marca')),
            ],
        ),
        migrations.CreateModel(
            name='ParamTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_param', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_procesador', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD'), ('Samsung', 'Samsung'), ('Mediatek', 'Mediatek'), ('Qualcomm', 'Qualcomm'), ('Unisoc', 'Unisoc')], max_length=20, verbose_name='Marca Procesador')),
                ('modelo_p', models.CharField(max_length=20, verbose_name='Modelo')),
                ('ghz', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Ghz')),
                ('nucleos', models.IntegerField(verbose_name='Cores')),
                ('año_mf', models.IntegerField(verbose_name='Año manufactura')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=50)),
                ('empresa', models.CharField(max_length=20)),
                ('gerente', models.CharField(max_length=20)),
                ('centro_de_costo', models.CharField(choices=[('Supervision Ja', 'Supervision Ja'), ('Supervision Gc', 'Supervision Gc'), ('Supervision CVS', 'Supervision CVS'), ('Administracion', 'Administracion'), ('Parentales', 'Parentales'), ('Comex', 'Comex'), ('Planta', 'Planta'), ('Ventas', 'Ventas'), ('HomeFarm', 'HomeFarm'), ('Operaciones Agricolas', 'Operaciones Agricolas'), ('Laboratiorio', 'Laboratiorio'), ('Plantas de Maiz', 'Plantas de Maiz')], max_length=25, verbose_name='Centro de Costo')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.departamentos')),
            ],
            options={
                'verbose_name': 'Trabajadores',
            },
        ),
        migrations.CreateModel(
            name='Tablets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_tablet', models.CharField(max_length=20, unique=True)),
                ('imei_tb', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_compra_tablet', models.DateField(help_text='Fecha en la que se recepciona el equipo en la empresa')),
                ('valor_tablet', models.IntegerField(help_text='Por favor inserte el valor en CLP')),
                ('observaciones_tablets', models.CharField(blank=True, max_length=50)),
                ('tram', models.IntegerField(verbose_name='Memoria Ram')),
                ('estado_tablet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.estados')),
                ('modelo_tablet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.modelos')),
            ],
        ),
        migrations.CreateModel(
            name='Smartphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_smartphone', models.CharField(max_length=20, unique=True)),
                ('imei1', models.IntegerField(unique=True)),
                ('imei2', models.IntegerField(null=True, unique=True)),
                ('fecha_compra_telefono', models.DateField(help_text='Fecha en la que se recepciona el equipo en la empresa')),
                ('valor_telefono', models.IntegerField(help_text='Por favor inserte el valor en CLP')),
                ('observaciones_telefonos', models.CharField(blank=True, max_length=50)),
                ('sram', models.IntegerField(verbose_name='Memoria Ram')),
                ('estado_telefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.estados')),
                ('modelo_smartphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.modelos')),
            ],
        ),
        migrations.CreateModel(
            name='Num_telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tel', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.estados')),
            ],
            options={
                'verbose_name': 'Telefono',
            },
        ),
        migrations.CreateModel(
            name='Notebooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_notebook', models.CharField(max_length=20, unique=True)),
                ('fecha_compra_notebook', models.DateField(help_text='Fecha en la que se recepciona el equipo en la empresa')),
                ('valor_notebook', models.IntegerField(help_text='Por favor inserte el valor en CLP')),
                ('observaciones_notebook', models.CharField(blank=True, max_length=50)),
                ('nram', models.IntegerField(verbose_name='Memoria Ram')),
                ('nhdd', models.IntegerField(help_text='Por favor marcar 0 si no tiene HDD', verbose_name='HDD')),
                ('nssd', models.IntegerField(help_text='Por favor marcar 0 si no tiene SSD', verbose_name='SSD')),
                ('estado_notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.estados')),
                ('modelo_notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.modelos')),
            ],
        ),
        migrations.AddField(
            model_name='modelos',
            name='m_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.paramtipo'),
        ),
        migrations.AddField(
            model_name='modelos',
            name='m_procesador',
            field=models.ForeignKey(default='01', help_text="Por favor marcar 'No aplica' para las camionetas", on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.procesador'),
        ),
        migrations.CreateModel(
            name='Mantenciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantencion', models.DateField(default=None)),
                ('m_kilometraje', models.IntegerField(verbose_name='Kilometraje aproximado de la mantencion')),
                ('m_estado', models.BooleanField(default=False)),
                ('m_patente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.camionetas')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.asignacion')),
            ],
        ),
        migrations.AddField(
            model_name='camionetas',
            name='disponible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.estados'),
        ),
        migrations.AddField(
            model_name='camionetas',
            name='modelo_camioneta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.modelos'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='camionetas_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.camionetas'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='notebook_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.notebooks'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.num_telefono'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='smartphone_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.smartphones'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='tablet_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.tablets'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.usuarios'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='vigente',
            field=models.ForeignKey(help_text='marcar si es la asignacion actual del usuario.', on_delete=django.db.models.deletion.CASCADE, to='dashboard.estados'),
        ),
    ]
