# Generated by Django 4.0.4 on 2022-05-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.usuarios'),
        ),
    ]
