# Generated by Django 4.0.4 on 2022-05-31 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_equipos_observaciones_alter_equipos_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='Telefono',
            new_name='telefono',
        ),
    ]
