# Generated by Django 4.1.7 on 2023-03-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_asignacion_vigente_alter_camionetas_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camionetas',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camionetas',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
