# Generated by Django 4.1.7 on 2023-03-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_camionetas_fecha_entrega_camionetas_fecha_recepcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='num_telefono',
            name='activo',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='num_telefono',
            name='numero_tel',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='Numero'),
        ),
    ]
