# Generated by Django 4.1.7 on 2023-03-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_num_telefono_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='num_telefono',
            name='activo',
            field=models.BooleanField(verbose_name='contratado'),
        ),
        migrations.AlterField(
            model_name='smartphones',
            name='imei1',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='smartphones',
            name='imei2',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
