# Generated by Django 4.1.7 on 2023-03-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_num_telefono_activo_alter_smartphones_imei1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camionetas',
            name='observaciones_camionetas',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modelos',
            name='m_modelo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='observaciones_notebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='smartphones',
            name='observaciones_telefonos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tablets',
            name='observaciones_tablets',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
