# Generated by Django 4.0.4 on 2022-06-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_usuarios_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='num_telefono',
            name='numero_tel',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
