# Generated by Django 4.0.4 on 2022-06-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_num_telefono_numero_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='area',
            field=models.ForeignKey(on_delete=models.SET('.'), to='dashboard.departamentos'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.ForeignKey(on_delete=models.SET('.'), to='dashboard.num_telefono'),
        ),
    ]
