# Generated by Django 4.1.7 on 2023-03-25 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_camionetas_observaciones_camionetas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='camionetas_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.camionetas', verbose_name='Camioneta'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_cm',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Feha de entrega'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_nt',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_sma',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_ta',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='notebook_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.notebooks', verbose_name='Notebook'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.num_telefono', verbose_name='Numero de telefono'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='smartphone_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.smartphones', verbose_name='Smartphone'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='tablet_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.tablets', verbose_name='Tablet'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.usuarios', verbose_name='Trabajador'),
        ),
        migrations.AlterField(
            model_name='smartphones',
            name='imei2',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
