# Generated by Django 4.0.4 on 2022-06-03 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_usuarios_area_alter_usuarios_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.departamentos'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.num_telefono'),
        ),
    ]
