# Generated by Django 4.1.7 on 2023-04-04 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_asignacion_camionetas_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='area',
        ),
        migrations.DeleteModel(
            name='Departamentos',
        ),
    ]
