# Generated by Django 4.1.7 on 2023-04-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_usuarios_area_delete_departamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebooks',
            name='mantencion_notebook',
            field=models.DateField(default='2023-1-1', help_text='Fecha de la ultima mantecion'),
            preserve_default=False,
        ),
    ]
