# Generated by Django 4.0.4 on 2022-06-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_usuarios_area_alter_usuarios_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='area',
            field=models.ForeignKey(on_delete=models.SET('0'), to='dashboard.departamentos'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.ForeignKey(on_delete=models.SET('0'), to='dashboard.num_telefono'),
        ),
    ]
