# Generated by Django 4.0.4 on 2022-06-03 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_num_telefono_numero_tel_alter_usuarios_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.series'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.usuarios'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.equipos'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.usuarios'),
        ),
    ]
