# Generated by Django 4.1.7 on 2023-03-07 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_historial_equipo_alter_historial_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente', models.BooleanField(help_text='marcar si es la asignacion actual del usuario.')),
            ],
        ),
        migrations.CreateModel(
            name='Camionetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('mantencion', models.DateField()),
                ('observaciones_camionetas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_modelo', models.CharField(max_length=20, unique=True)),
                ('m_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Notebooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_notebook', models.CharField(max_length=20, unique=True)),
                ('fecha_compra_notebook', models.DateField(help_text='Fecha en la que se recepciona el equipo en la empresa')),
                ('valor_notebook', models.IntegerField(help_text='Por favor inserte el valor en CLP')),
                ('observaciones_notebook', models.CharField(blank=True, max_length=50)),
                ('modelo_notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.modelos')),
            ],
        ),
        migrations.CreateModel(
            name='ParamTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_param', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Smartphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_smartphone', models.CharField(max_length=20, unique=True)),
                ('imei1', models.IntegerField(unique=True)),
                ('imei2', models.IntegerField(null=True, unique=True)),
                ('estado_telefono', models.BooleanField(default=True)),
                ('fecha_compra_telefono', models.DateField(help_text='Fecha en la que se recepciona el equipo en la empresa')),
                ('valor_telefono', models.IntegerField(help_text='Por favor inserte el valor en CLP')),
                ('funciona_telefono', models.BooleanField(default=True)),
                ('observaciones_telefonos', models.CharField(blank=True, max_length=50)),
                ('modelo_smartphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.modelos')),
            ],
        ),
        migrations.CreateModel(
            name='Tablets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_tablet', models.CharField(max_length=20, unique=True)),
                ('imei_tb', models.CharField(max_length=20, null=True, unique=True)),
                ('fecha_compra_tablet', models.DateField(help_text='Fecha en la que se recepciona el equipo en la empresa')),
                ('valor_tablet', models.IntegerField(help_text='Por favor inserte el valor en CLP')),
                ('observaciones_tablets', models.CharField(blank=True, max_length=50)),
                ('modelo_tablet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.modelos')),
            ],
        ),
        migrations.RemoveField(
            model_name='historial',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='telefono',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='num_telefono',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rut',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Equipos',
        ),
        migrations.DeleteModel(
            name='historial',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.AddField(
            model_name='modelos',
            name='m_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.paramtipo'),
        ),
        migrations.AddField(
            model_name='camionetas',
            name='modelo_camioneta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.modelos'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='camionetas_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.camionetas'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='notebook_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.notebooks'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.num_telefono'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='smartphone_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.smartphones'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='tablet_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tablets'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.usuarios'),
        ),
    ]
