# Generated by Django 4.1.7 on 2023-03-07 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_asignacion_camionetas_marca_modelos_notebooks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.num_telefono'),
        ),
    ]
