# Generated by Django 4.1.7 on 2023-03-10 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_asignacion_num_alter_num_telefono_numero_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_equipos', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='smartphones',
            name='funciona_telefono',
        ),
        migrations.AlterField(
            model_name='num_telefono',
            name='numero_tel',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='camionetas',
            name='disponible',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.estados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooks',
            name='estado_notebook',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.estados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablets',
            name='estado_tablet',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.estados'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='vigente',
            field=models.ForeignKey(help_text='marcar si es la asignacion actual del usuario.', on_delete=django.db.models.deletion.CASCADE, to='dashboard.estados'),
        ),
        migrations.AlterField(
            model_name='num_telefono',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.estados'),
        ),
        migrations.AlterField(
            model_name='smartphones',
            name='estado_telefono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.estados'),
        ),
    ]
