# Generated by Django 4.1.7 on 2023-03-10 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_estados_remove_smartphones_funciona_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='fecha_cm',
            field=models.DateField(default=datetime.date(2023, 3, 10)),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='fecha_nt',
            field=models.DateField(default=datetime.date(2023, 3, 10)),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='fecha_sma',
            field=models.DateField(default=datetime.date(2023, 3, 10)),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='fecha_ta',
            field=models.DateField(default=datetime.date(2023, 3, 10)),
        ),
    ]
