# Generated by Django 4.1.7 on 2023-03-10 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_asignacion_fecha_cm_asignacion_fecha_nt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_sma',
            field=models.DateField(default=datetime.datetime(2023, 3, 10, 22, 54, 50, 724510, tzinfo=datetime.timezone.utc)),
        ),
    ]
