# Generated by Django 4.1.7 on 2023-03-10 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_asignacion_fecha_sma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_cm',
            field=models.DateField(default=datetime.datetime(2023, 3, 10, 22, 55, 48, 726225, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_nt',
            field=models.DateField(default=datetime.datetime(2023, 3, 10, 22, 55, 48, 726225, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_sma',
            field=models.DateField(default=datetime.datetime(2023, 3, 10, 22, 55, 48, 726225, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_ta',
            field=models.DateField(default=datetime.datetime(2023, 3, 10, 22, 55, 48, 726225, tzinfo=datetime.timezone.utc)),
        ),
    ]
