# Generated by Django 4.1.7 on 2023-03-11 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_asignacion_camionetas_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_cm',
            field=models.DateField(default=datetime.datetime(2023, 3, 11, 2, 9, 48, 959746, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_nt',
            field=models.DateField(default=datetime.datetime(2023, 3, 11, 2, 9, 48, 959746, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_sma',
            field=models.DateField(default=datetime.datetime(2023, 3, 11, 2, 9, 48, 959746, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_ta',
            field=models.DateField(default=datetime.datetime(2023, 3, 11, 2, 9, 48, 959746, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
