# Generated by Django 4.1.7 on 2023-03-11 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_asignacion_fecha_cm_alter_asignacion_fecha_nt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_cm',
            field=models.DateField(default=datetime.datetime(2023, 3, 11, 2, 12, 27, 202094, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_nt',
            field=models.DateField(default=datetime.datetime(2023, 3, 11, 2, 12, 27, 202094, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_sma',
            field=models.DateField(default=datetime.datetime(2023, 3, 11, 2, 12, 27, 202094, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_ta',
            field=models.DateField(default=datetime.datetime(2023, 3, 11, 2, 12, 27, 202094, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
