# Generated by Django 4.1.7 on 2023-03-11 19:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_asignacion_fecha_cm_alter_asignacion_fecha_nt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='camionetas_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.camionetas'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_cm',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 11, 19, 10, 35, 832359, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_nt',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 11, 19, 10, 35, 832359, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_sma',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 11, 19, 10, 35, 832359, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_ta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 11, 19, 10, 35, 832359, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='notebook_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.notebooks'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='tablet_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.tablets'),
        ),
    ]
