# Generated by Django 4.1.7 on 2023-03-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_asignacion_fecha_cm_alter_asignacion_fecha_nt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_procesador', models.CharField(max_length=20)),
                ('modelo_p', models.CharField(max_length=20)),
                ('ghz', models.IntegerField()),
                ('nucleos', models.IntegerField()),
                ('año_mf', models.IntegerField()),
            ],
        ),
    ]
