# Generated by Django 4.1.7 on 2023-03-16 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_procesador'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelos',
            name='m_procesador',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.procesador'),
        ),
    ]
