# Generated by Django 4.1.7 on 2023-03-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_modelos_m_procesador'),
    ]

    operations = [
        migrations.AddField(
            model_name='camionetas',
            name='modalidad',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camionetas',
            name='vin',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
