# Generated by Django 4.1.7 on 2023-03-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_camionetas_modalidad_camionetas_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesador',
            name='año_mf',
            field=models.IntegerField(verbose_name='Año manufactura'),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='ghz',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Ghz'),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='marca_procesador',
            field=models.CharField(max_length=20, verbose_name='Marca Procesador'),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='modelo_p',
            field=models.CharField(max_length=20, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='nucleos',
            field=models.IntegerField(verbose_name='Cores'),
        ),
    ]
