# Generated by Django 4.1.7 on 2023-03-18 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_procesador_año_mf_alter_procesador_ghz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='centro_de_costo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='empresa',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='gerente',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelos',
            name='m_procesador',
            field=models.ForeignKey(default='01', help_text="Por favor marcar 'No aplica' para las camionetas", on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.procesador'),
        ),
    ]
