# Generated by Django 4.1.7 on 2023-03-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_usuarios_centro_de_costo_usuarios_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camionetas',
            name='modalidad',
            field=models.CharField(choices=[('Leasing', 'Leasing'), ('Rental', 'Rental Car')], max_length=20, verbose_name='listado modalidades'),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='area',
            field=models.CharField(choices=[('Administracion', 'Administracion'), ('Terreno', 'Terreno'), ('Planta', 'Planta')], max_length=20, null=True, verbose_name='Listado Areas'),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='sucursal',
            field=models.CharField(choices=[('Bulnes', 'Bulnes'), ('Talca', 'Talca'), ('Chillan', 'Chillan'), ('Peru', 'Peru')], max_length=20, verbose_name='listado sucursales'),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='marca_procesador',
            field=models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD'), ('Samsung', 'Samsung'), ('Mediatek', 'Mediatek'), ('Qualcomm', 'Qualcomm'), ('Unisoc', 'Unisoc')], max_length=20, verbose_name='Marca Procesador'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='centro_de_costo',
            field=models.CharField(choices=[('Supervision Ja', 'Supervision Ja'), ('Supervision Gc', 'Supervision Gc'), ('Supervision CVS', 'Supervision CVS'), ('Administracion', 'Administracion'), ('Parentales', 'Parentales'), ('Comex', 'Comex'), ('Planta', 'Planta'), ('Ventas', 'Ventas'), ('HomeFarm', 'HomeFarm'), ('Operaciones Agricolas', 'Operaciones Agricolas'), ('Laboratiorio', 'Laboratiorio'), ('Plantas de Maiz', 'Plantas de Maiz')], max_length=25, verbose_name='Centro de Costo'),
        ),
    ]
