# Generated by Django 4.1.7 on 2023-03-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_rename_ram_notebooks_nram_remove_notebooks_hdd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphones',
            name='sram',
            field=models.IntegerField(default=1, verbose_name='Memoria Ram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablets',
            name='tram',
            field=models.IntegerField(default=1, verbose_name='Memoria Ram'),
            preserve_default=False,
        ),
    ]
