# Generated by Django 4.1.7 on 2023-03-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_smartphones_sram_tablets_tram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablets',
            name='imei_tb',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
