# Generated by Django 4.1.7 on 2023-03-21 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_alter_num_telefono_options_alter_usuarios_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='camionetas',
            name='kilometraje',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Mantenciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantencion', models.DateField(default=None)),
                ('m_kilometraje', models.IntegerField()),
                ('m_estado', models.BooleanField(default=False)),
                ('m_patente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.camionetas')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.usuarios')),
            ],
        ),
    ]
