# Generated by Django 4.1.7 on 2023-03-21 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_camionetas_kilometraje_mantenciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenciones',
            name='m_patente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.asignacion'),
        ),
    ]
