# Generated by Django 4.1.7 on 2023-03-21 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_alter_mantenciones_m_patente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenciones',
            name='m_kilometraje',
            field=models.IntegerField(verbose_name='Kilometraje aproximado de la mantencion'),
        ),
        migrations.AlterField(
            model_name='mantenciones',
            name='m_patente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.camionetas'),
        ),
        migrations.AlterField(
            model_name='mantenciones',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.asignacion'),
        ),
    ]
